# deploy.yml

name: Deploy Node.js App to ECR

on:
  push: 
   branches: 
     - 'master'

jobs:
    build:
       name: Build Image
       runs-on: ubuntu-latest
       
       steps:
           - name : Check variables 
             run: echo $AWS_REGION  $vars.AWS_REGION ${{vars.AWS_REGION}}
           - name: Check out code
             uses: actions/checkout@v2 # deploy.yml

           - name: Configure AWS credentials
             uses: aws-actions/configure-aws-credentials@v1
             with:
                   aws-access-key-id: $
                   aws-secret-access-key: $
                   aws-region: $
           
           # deploy.yml
           - name: Login to Amazon ECR
             id: login-ecr
             uses: aws-actions/amazon-ecr-login@v1
           
           
           # deploy.yml
           - name: Build, tag, and push image to Amazon ECR
             env:
               ECR_REGISTRY: $
               ECR_REPOSITORY: simple_nodejs_app
               IMAGE_TAG: nodejs_simple_app
             run: |
               docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
               docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
           
